project:
  type: book

book:
  title: "Chronic Pain and Social Reform"
  author: "Luke Slipski"
  date: today
  chapters:
    - index.qmd
    - tech_and_chronic_pain.qmd
    - neuroscience_and_chronic_pain.qmd
    - social_physical_therapy.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

