project:
  type: book

book:
  title: "Chronic Pain and Social Reform"
  author: "Luke Slipski"
  date: today
  chapters:
    - index.qmd

format:
  html:
    theme: 
      light: [cosmo, styles.scss]

editor: visual

