project:
  type: book

book:
  title: "Chronic Pain and Social Reform"
  author: "Luke Slipski"
  date: today
  chapters:
    - index.qmd
    - tech_and_chronic_pain.qmd
    - neuroscience_and_chronic_pain.qmd
    - limits_of_tech.qmd
    - social_physical_therapy.qmd
    - references.qmd
  downloads: [pdf]
bibliography: references.bib

format:
  html:
    theme: [cosmo, styles.scss]
  pdf:
    documentclass: scrreprt

editor: visual

