project:
  type: book

book:
  title: "Chronic Pain and Social Reform"
  author: "Luke Slipski"
  date: today
  chapters:
    - index.qmd
    - tech_and_chronic_pain.qmd
    - neuroscience_and_chronic_pain.qmd
bibliography: references.bibtex
csl: diabetologia.csl

format:
  html:
    theme: 
      light: [cosmo, styles.scss]
      dark: [darkly, styles.scss]
    embed-resources: true

