# Preface {.unnumbered}

This series of essays is about chronic pain and the methods we employ to address it. I believe the best tools for preventing and treating pain pathologies already exist. However these tools, which I collectively refer to as "social reform", are not easy or straightforward to wield. Social reform's targets are not always precisely defined. And most importantly, social reform works in opposition to the billionaire class, their profits, and the conditions they insist on for workers around the world.

Biologists will argue that chronic pain is a pathology of sodium channel abnormalities. Most clinicians will argue that it is a pathology of aberrant neuromuscular or musculoskeletal physiology. Neuroscientists will argue that it is a pathology of complex changes of information processing in the central nervous system. But these scientific conceptions are all myopic half-truths.

Chronic pain is a pathology of society. The simple epidemiological finding that ought to stop pain researchers in their tracks is the fact that chronic pain is more common among the poor [-@cdc-pain-prev; -@pain-prev-us]. This grounding of pain in the social order is something an individual-level approach to pain can never address. Treating a person's chronic pain, only to release them back into a pain-producing, nocigenic environment, is stopgap medicine. It is a temporary relief that does nothing to address the cause of pain at its origin. To treat the cause instead of the symptom will require social reform. But again, social reform is arduous, political, and defies the capitalist class.

Instead, we have turned to the will-o'-the-wisp of technological solutions. Leading ourselves on, we chase the conceit of a high tech quick fix that is far more nebulous than the goals of social reform. Such a hope is incoherent in light of the societal causes of chronic pain, but its glow through the fog keeps us wandering down a fruitless path. On the journey, we first turned to the high technology of Big Pharma, which brought us the decades-long opioid epidemic [-@cdc_opioid_epidemic]. In the wake of this spectacular failure have come various treatment strategies rooted primarily in digital technology. These efforts are doomed to fail as well. Technological innovation for the treatment of chronic pain will only be successful insofar as it amplifies and interfaces with broad social reform efforts. It is this difficult truth that I explore in the following essays.

I will point out now that I am not categorically opposed to new technology. But the writing has been on the exposed brick walls of Silicon Valley health tech offices for a long time. The Invisible Hand of the market can only offer a haphazard and uncaring approach to technological advancement, and it produces, by and large, expensive garbage.

I first came to understand the societal origins of chronic pain through my work [-@luke-stand] with STAND: The Haiti Project [-@stand]. My efforts to document and understand the rampant reports of pain experienced by our patients in rural Haiti have spanned my schooling and professional life. After my formal education in public health, I launched headlong down the high tech-health rabbit hole, building a career that straddled the tech worlds of both industry and academia. When the disillusionment of high technology set in, I found myself back where I started: considering the condition of the working class. It is through the lenses of public health, technology, and socialism, that I explore the interrelationship of chronic pain and social reform.

### Public Health

I got to know the Public Health 101 professor while working on a smoking prevention project with her in India. I had been pre-pre-med since the 6th grade, and in my sophomore year of undergrad I chose the University of Rochester's "Health, Behavior, and Society" major primarily because I thought it would look good on a medical school application. And I wasn't the only one with this idea. The major was teeming with neurotic and preening pre-meds all angling for a spot in the best medical schools so that they could better angle for a spot in the best residencies.

"Notorious" is too strong a word, but it was known among the public health majors that Dr. Chin [-@nancy-chin] encouraged pre-medical students to think broadly about their career options beyond any hospital. As opportunist as we were, most of us also arrived with a commensurate dose of idealism. We wanted to change the world. With some of this in mind, we were sipping our chais and looking out at the foothills of the Himalayas when she finally dropped the question on me.

> ##### I don't get it. Why do all these smart, motivated young people who want to change the world go into *medicine*?
>
> ##### - Nancy Chin {.quote-attribution}

I responded with some amalgamation of all the platitudes frequently used to inculcate young people into a paradigm of health and health morality that spotlights doctors as heroes. What she was really asking was, "What do you think makes people healthy? Is it really *medicine*?"

And then we moved on. Because Dr. Chin isn't in the business of telling students what to do. Apparently, her MO is patiently asking students perspicacious questions at indelible moments that will haunt them throughout an adulthood full of mistakes and corrections. The following essays are an attempt to synthesize my learnings from years down a path of trying to address the chronic pain pandemic through a technocratic, treatment-centered approach. They serve as a course correction to the intoxicating arrogance that posits an ever deeper, more scientific, more data-driven understanding of chronic pain can single handedly solve the suffering seen around the world today. Unlike Dr. Chin, professors espousing this high technologic worldview *are* in the business of telling students what to do. And I was eager to take orders.

### Technology

I was accepted into Rochester's Take 5 Program and granted a tuition-free fifth year to take classes in a field I hadn't had time to study while completing my public health degree. I titled my application essay `Befriending Big Data and Nurturing the Human-Computer Relationship` and proposed taking a set of Math, Computer Science, and Brain & Cognitive Science courses. It was during my Introduction to Java Programming class that I was first indoctrinated into the gospel of technology.

> ##### If you want to change the world, learn how to code.
>
> ##### - Ted Pawlicki {.quote-attribution}

Pointing out the obvious impact apps like Facebook and Twitter had made on the world, Professor Pawlicki [-@ted-pawlicki] was arguing that computer programmers were the people making decisions that actually affect people day-to-day. Through the power of the internet, everyone can be touched by the code written on *your laptop*. Hot off a degree in public health, I interpreted this in some vague way to mean I could create tech that made people healthy. In fact, one of my Take 5 advisors was Henry Kautz, whose research had recently made headlines like Your Tweets Can Predict When You'll Get the Flu [-@tweet-flu]. The obligatory comparison to John Snow [@johnsnow] was plenty to make me envisage my code as part of the impending Big Data revolution in epidemiology and health. This program equipped me with the holy trinity of the high tech-health worldview:

1.  A nebulous notion of how `more_technology == better`
2.  The suggestion that anyone (including me!) could be the hero who writes the code that saves the lives
3.  Some tangible coding skills to immediately start becoming a hero

With some java and python skills under my belt I went on to complete my MPH at the University of California Davis, spending most of my study time learning to connect public health databases with analytic programming languages. This paid off when I was accepted to the first cohort of Kaiser Permanente's "Programmer/Analyst Training Program." At Kaiser I learned SAS programming, some more statistics, and how to carry out a digital cohort study. My next job was at an electronic medical records (EMR) company called Practice Fusion. It was here my eyes were opened to what scourge the health tech sector is capable of wreaking.

Practice Fusion brought me a high salary, catered lunches, beer and wine on tap, and huge parties. And we were working on a product that helped patients! Right? RIGHT?! I learned a lot of programming there. And our mission was ostensibly to build a free EMR to help bring small doctors' offices into the 21st century. We were going to combine their medical records and do important epidemiology, which would, in turn, even further benefit patients! Where is the harm in that?

It is exactly this sort of hard-to-argue-with *symbolism*, of technology as progress, that I hope to cross-examine in this writing. Because who doesn't want to appropriate the Algorithms to help cure disease? Who doesn't want people to have access to "precision medicine," where capital "B" capital "D" Big Data is utilized to help doctors make hyperpersonalized medical decisions? It is hard for anyone who doesn't spend all day rummaging around in this data to articulate why it might not be the best investment. Even those of us most entrenched in the industry's dirty technical details fall for the same abstract promises CEOs continue to sell to investors. Because remember, this technology is going to

ðŸ‘ *Change*.ðŸ‘

ðŸ‘ *The*.ðŸ‘

ðŸ‘ *World*.ðŸ‘

After a few years at Practice Fusion, I got tired of working with EMR data and left. It is worth mentioning that shortly after leaving I learned the company had been pushing opioids to patients for chump change [@pf-opioids]. Anything to keep the startup dream alive though right? At any rate, I suspected our EMR studies weren't telling us anything meaningful. I decided that I needed to venture further into the technical weeds if I was going to find quality enough data to...err...change the world(?). Or whatever Professor Pawlicki had sold me. It sounded so cool when he said it.

I left Silicon Valley and moved to Boulder, Colorado to work as a research assistant in a "famous" neuroscience lab. Having watched an entire Youtube series on fancy statistical analytic methods using functional magnetic resonance imaging data, I was convinced that this was the field I needed to dig into if I were going to be the one to solve chronic pain. The lab moved to Dartmouth the following year, and I was accepted as a PhD student there.

At Dartmouth I spent a lot of time thinking about how to find specific patterns of brain activity called "biomarkers" that would tell us when a person is experiencing various types of pain. You see, the lab I belonged to was already known for developing this type of biomarker for acute thermal pain. If you burned someone's arm inside of an fMRI scanner, this biomarker would light up. However, if you only warmed up someone's arm or showed them a picture of their ex-lover while in the scanner, the biomarker wouldn't light up as much. Pretty neat, right? Further, one of the main selling points is that these biomarkers are made using ðŸ§™ *machine learning* ðŸ§™ . And when I say "selling point", I mean millions [@a2cps1] and millions [@a2cps2] and millions [@a2cps3] and millions [@a2cps4] and millions [@a2cps5] of NIH dollars are being funneled into the pain biomarkers enterprise [@a2cps].

I remember taking long walks at Dartmouth and explaining this research to my friends on the phone. With varying degrees of tenderness, the conversation would always lead to the question "so like, let's say you had all these biomarkers. And they worked. Then what? Is the plan to put all pain patients one-by-one into an fMRI scanner for an hour just to arrive at a more 'objective' measure of the pain they already told you they have?" I knew, deep in my bones, that this was a legitimate question with no good answer. I usually said something like "as a neuroscientist, health care delivery isn't my problem."

This is, I now argue, a useless-at-best position. But this is the position of huge swaths of publicly-funded biotech research today. It is the *de facto* excuse that allows the private and academic high tech-health sectors to squander unconscionable sums of money each year advancing technology that is either obviously impotent or so inaccessible to the global working class that it is effectively non-existent. It is a feckless pursuit to develop high technology without incorporating class consciousness. I now believe it is only in tandem with efforts toward broad social improvement that high technology can be useful in improving the health of ordinary people around the world.

My time in the Ivory Tower indirectly led me to socialist politics. The most important lesson I learned in my neuroscience PhD work (before leaving early) was that organized labor is central in shaping health and well-being. [Conversely, the biggest regret I have from my time in New Hampshire is that I didn't stick around long enough to witness and support the expert-level organizing that won Dartmouth grad students their union [@gold-ue].]{.aside} As I documented in "The Dartmouth Prison Experiment" [@dartmouth-prison], a defining characteristic of academic high tech science is extracting cheap labor through the promise and mirage of heroism. The cringe and irony involved in watching a pain-neuroscience lab foster a toxic culture of stress and overwork is itself painful. But this example also explicates the essence of what the following essays are about. Even in the closest proximity to brain scans, the avant-garde of pain regulation science, and health-tech heroes, it is working and living conditions that drive the quality of our lives.

Toward the end of my Dartmouth sojourn I joined the Upper Valley Democratic Socialists of America [@uvdsa] in their Care not Cops campaign. In some ways this was a totally new experience to me. I had never gone door-to-door before to discuss politics with other community members. Nor had I given public comment to a city council. But in other ways joining DSA was a return to form. Before my Dartmouth degree, before my tech jobs and my infatuation with high health-technology, before I had written even a single line of code, way back before I even took Public Health 101 with Nancy Chin, I signed up for my first public health course to see if the field might be a good fit for me. Departing the fog of an ill-conceived career in neuroscience, I found myself digging out old books I bought for *History 208: Health, Medicine, and Social Reform*.

### Social Reform

Ted Brown [@ted-brown] walked in, as was his custom, with a few pieces of paper covered in handwritten notes. The elbows of his worn, burgundy sweater were patched where he rested them on the podium as he began his lecture. Ninety minutes at a time, I was pummeled with evidence demonstrating the ways health is grounded in the social order. I hadn't known how simultaneously incisive, scathing, hopeful, and compassionate a critical historical lens could be. I was forced to consider how Cuba, a small socialist country, could have equal or better health outcomes than the United States while paying drastically less for medical care. I learned how the failed Global Malaria Eradication Program relied so heavily on [vertical, technocratic approaches](@sec-malaria) to public health and how the Gates Foundation continues to apply technologic lipstick to new renditions of this humanitarian failure [@gates-grandest]. It was in this course I first read "The Condition of the Working Class in England" [@engels], and where I first heard of a person called Marx.

These lessons are the type that once you see them, you can never un-see them. Health, medicine, and social reform, from a socialist perspective, go a long way in explaining how the world works for people on planet earth. I was hooked on this type of analysis and took the rest of Ted's courses, one of which was an Introduction to the U.S. healthcare system. It was in this course that I picked up this mantra, which I've had stuck in my head over the last few years:

> ##### Every budget is a *moral* document.


What any group or society decides to pay for is a representation of what it values. I found myself thinking of this every time a lowly research assistant at Dartmouth was stuck running fMRI scans late into the evening after a full work day, fearful of punishment for any mistakes, having been told explicitly they would collect no overtime pay. All so we could...mmm...look for brain patterns that would...ermmm...help us predict when people who tell us they're in pain are...in pain. [I am aware that people in the field will be more or less outraged with this description of the pain biomarker endeavor and clamor to explain the nuances of what they do. I also think this issue is a fractal, and every deeper level of nuance reveals equal impotence of the "technology", even if it successfully confuses funding agencies.]{.aside} The lab's budget relied on the extraction of labor with impunity and the suppression of workers' wages, so that it could provide the Principal Investigator fame and fortune. [After publishing "The Dartmouth Prison Experiment", I received 2 final emails from Dartmouth. The first was from my former adviser, informing me that my writing only served to hurt him and the graduate student carrying out his orders. The second was from the Department Chair, whose email said, "I'm emailing you of course because of your blog post. I'm sorry that you had such a negative experience here, but I'm glad that you've described your concerns about the treatment of the RAs working on the Spacetop project. The new department administrator and I are looking into your concerns. It's already clear that some of the RAs were not properly compensated for the hours they worked." These research assistants were eventually and quietly back paid thousands of dollars. I don't know if any of that money came out of the lab's budget. I'm not aware of any departmental policies that were created to prevent worker mistreatment.]{.aside} And lots and lots of scans to build the brand. A huge proportion of this money came through public funding sources like the National Institutes of Health (NIH). If every budget is a moral document, is there a name for this flavor of morality? The lab's budget was a high-fidelity representation of health tech values under capitalism. Abuse of workers, high CEO salaries, flashy presentations promising a nebulous panacea that will never materialize, and no plan to make such a cure available to those who most need it; this is *our* morality when we throw our hands up and pray to the Invisible Hand for good health.

Outside of any individual lab, as I will argue in the following essays, the way the United States allocates its pain research money is a similar moral disaster. The government continues to budget for the *symbolism* of high tech magic bullets that will never arrive. At the same time, private equity firms pour billions into the creation of health tech startups that are not designed to, and will never, improve the lives of ordinary people. When the banks funding these useless companies fail, the government makes room in the budget to rescue them while stiffing low-income communities [@svb-low-income]. All this, while pain *prevention* researchers receive a pittance, and social safety nets for poor people, who are most at risk for developing chronic pain, fray and decay. Our budgets reflect our capitalist economy's moral values, and those moral values are ill-conceived, scandalous and repugnant.

I attended a webinar on February 24, 2023 hosted by the Canadian Pain Society titled, *"National Pain Rounds: Are We Treating Chronic Pain All Wrong?"* . There was a lot of hype around the event, and I remember seeing a tweet that read, "join us as we step back and ask big questions about how we are thinking about and treating chronic pain." The panel included physicians, psychology PhDs, and an advocate for people living with chronic pain. There was a lot of obligatory emphasis that pain is not "all in our heads". But there were no big questions and even fewer answers about what to do. A nod to mindfulness here, a recapitulation of some "new" psychological therapy there. The clinicians seemed excited to recount stories of patients they've seen whose experience in the workplace had something to do with their chronic pain. But their explanations, at their most wide reaching, centered on the interpersonal relationships of people with pain. Politics were not mentioned, and they seemed unaware of the ways in which societal structures might create pain-producing environments for patients. Having omitted this entire realm of the human experience on earth, the biggest question for pain clinicians today went unasked. Why should we expect psychological therapies and modern neuroscience to treat (let alone prevent) chronic pain, when it is a pestilence that is grounded in the social order?

It is this question, and questions about how we might effectively work towards a societal treatment for chronic pain, that I hope these essays begin to answer. The most beautiful thing about replacing technocratic approaches to chronic pain with social reformist solutions isn't that it's the correct thing to do to reduce the prevalence of chronic pain, but that it is the compassionate, human, and right thing to do to reduce all forms of suffering around the world. Let's get organized.

At the behest of Captain Ludd [@captain-ludd],

**Luke**

### References
