# Neuroscience and Chronic Pain {#sec-neurochapter}

Ironically, at the acme of modern cognitive neuroscientific theory lies a refutation of the neurobiological approach to the pain pandemic. [One](https://doi.org/10.1007/s13164-022-00666-6) of the most recent and promising [frameworks](https://doi.org/10.1038/s41583-022-00587-4) for understanding what the brain does is called "predictive coding". Put simply, the PC framework asserts that our qualitative experiences arise when our brains create hypotheses about the state of the world around us and then test those predictions. But when scrutinized, even this technical neuroscientific approach to pain control seems to support socialist preventive strategies over expensive neuroscientific treatment.

Imagine for a second that you're a brain: a dense set of 86 billion neurons trapped inside of a dark, wet cavern. You cannot directly see or hear or touch. Instead, you receive noisy electro-chemical signals that are related to what's going on around the skull you inhabit. The problem of figuring-out-what's-going-on-out-there requires combining these inputs to make an informed guess about the environment causing those signals in the first place. As you make informed guesses you receive immediate feedback as to whether or not they were correct via the next set of electro-chemical signals. Guess and check. Guess and check.

But you're smart. So you write down notes of specific guesses you made and how correct they turned out to be. Of course not all guesses get one line in your notebook. Things are crossed out, underlined, and bolded and circled in the margins. As you make and test your little guesses every second of every day for your entire life, you develop an extensive understanding of what various signals from your environment likely mean. Neuroscientists call this palimpsest of memories you have a "model" of the environment. It is a detailed user manual for the world you inhabit. Your model is a powerful thing.

Predictive coding theory emphasizes that conscious experiences are not simply the result of signals arriving at the brain. Your brain's model of the world sits between the world and your experience of it. Imagine walking into a shed in the afternoon on a hot day. On the ground is a coiled up piece of rope. Upon entering the shed your brain leafs through its notebook to the page that says "hot day, 2pm, shed in low light, small coil on the ground" and follows the arrow it drew to the note "THIS WAS A SNAKE ONCE!" And for a moment, you literally perceive the rope to be a snake.

The rope snake is a silly example of the power your model holds over your experience. It is also an example of an illusion; the rope wasn't a snake, after all. But what happens when the scary, caps lock warning in your notebook indicates exactly the situation you're currently facing?

A lot of people believe their chronic pain is the rope snake -- the pain is not actually there. But it's actually the second case -- your body is in serious danger!

[Some studies](https://www.sciencedirect.com/science/article/pii/S0896627314001925?via%3Dihub) have shown that people who expect an upcoming stimulus to be painful experience stronger pain than those who expect a benign stimulus. And the more certain they are that pain is coming, the stronger they feel it. In fact, many chronic pain patients are now being diagnosed with "primary", "nonspecific", "nociplastic", or "centralized" pain. These are essentially synonyms for when clinicians find the volume knob for a patient's pain signals is inexplicably high. It is [estimated](https://jamanetwork.com/journals/jamapsychiatry/fullarticle/2784694) that in 85% of chronic back pain cases, the most common type of persistent pain, no definitive source of bodily harm can be found.

So where is all this pain coming from? In the context of PC, the absence of bodily damage means there shouldn't be strong bottom-up pain signals. And yet, day in and day out, people are experiencing debilitating pain. If chronic pain isn't coming from the sensorium, a good guess as to where it originates is a person's model of the world. Faced with a lack of social safety nets, a compulsion to sell one's labor, and the ever looming threats of joblessness, homelessness, and poverty, how could we expect the human brain to predict much other than "Pain! Pain! Pain!"? Our 86 billion neurons curate a sophisticated model of the expanse of an avaricious civilization, and the truth they discover hurts.
